use p256::ecdsa::signature::Signer;
use p256::ecdsa::signature::Verifier;
use p256::ecdsa::{Signature, SigningKey, VerifyingKey};
use p256::elliptic_curve::sec1::ToEncodedPoint;
use p256::SecretKey;
use rand::rngs::OsRng;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::association::AssociationKeypair;
use crate::crypto::{decrypt_mwa_message, derive_session_key, SessionKey};
use crate::error::{Result, ShaheenError};
use crate::sequence::SequenceTracker;

/// Ephemeral ECDH keypair generated by the dApp for a single session.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct DappEphemeralKeypair {
    #[zeroize(skip)]
    pub public_key_bytes: [u8; 65],
    private_key_bytes: [u8; 32],
}

impl DappEphemeralKeypair {
    pub fn generate() -> Result<Self> {
        let secret = SecretKey::random(&mut OsRng);
        let public = secret.public_key();
        let encoded_point = public.to_encoded_point(false);
        let pub_bytes = encoded_point.as_bytes();

        if pub_bytes.len() != 65 {
            return Err(ShaheenError::CryptoError(format!(
                "Unexpected public key length: expected 65, got {}",
                pub_bytes.len()
            )));
        }

        let mut public_key_bytes = [0u8; 65];
        public_key_bytes.copy_from_slice(pub_bytes);

        let mut private_key_bytes = [0u8; 32];
        private_key_bytes.copy_from_slice(&secret.to_bytes());

        Ok(Self {
            public_key_bytes,
            private_key_bytes,
        })
    }

    pub fn secret_key(&self) -> Result<SecretKey> {
        SecretKey::from_slice(&self.private_key_bytes)
            .map_err(|e| ShaheenError::CryptoError(format!("Invalid secret key bytes: {}", e)))
    }
}

/// Constructs the official MWA HELLO_REQ payload:
/// `<Qd (65 bytes)><Sa (64 bytes)>` = 129 bytes
///
/// - Qd is the X9.62 uncompressed ephemeral ECDH public keypoint of the dapp.
/// - Sa is the P1363-encoded ECDSA-SHA256 signature over Qd using the association keypair da.
pub fn build_hello_req(
    association_keypair: &AssociationKeypair,
    dapp_ephemeral: &DappEphemeralKeypair,
) -> Result<Vec<u8>> {
    let assoc_secret = association_keypair.secret_key()?;
    let signing_key = SigningKey::from(&assoc_secret);

    // Sign Qd (the 65-byte uncompressed public key)
    let signature: Signature = signing_key.sign(&dapp_ephemeral.public_key_bytes);
    let sa_bytes = signature.to_bytes(); // IEEE P1363 format: r || s (64 bytes)

    if sa_bytes.len() != 64 {
        return Err(ShaheenError::CryptoError(format!(
            "Unexpected signature length: expected 64, got {}",
            sa_bytes.len()
        )));
    }

    let mut hello_req = Vec::with_capacity(65 + 64);
    hello_req.extend_from_slice(&dapp_ephemeral.public_key_bytes);
    hello_req.extend_from_slice(&sa_bytes);

    Ok(hello_req)
}

/// Verifies a HELLO_REQ message against an association public key Qa (used by wallets/tests).
pub fn verify_hello_req(association_pub_bytes: &[u8; 65], hello_req_bytes: &[u8]) -> Result<[u8; 65]> {
    if hello_req_bytes.len() != 129 {
        return Err(ShaheenError::HandshakeError(format!(
            "Invalid HELLO_REQ length: expected 129, got {}",
            hello_req_bytes.len()
        )));
    }

    let qd_bytes: [u8; 65] = hello_req_bytes[0..65].try_into().unwrap();
    let sa_bytes: [u8; 64] = hello_req_bytes[65..129].try_into().unwrap();

    let verifying_key = VerifyingKey::from_sec1_bytes(association_pub_bytes)
        .map_err(|e| ShaheenError::CryptoError(format!("Invalid association public key: {}", e)))?;

    let signature = Signature::from_bytes(&sa_bytes.into())
        .map_err(|e| ShaheenError::CryptoError(format!("Invalid signature encoding: {}", e)))?;

    verifying_key
        .verify(&qd_bytes, &signature)
        .map_err(|e| ShaheenError::HandshakeError(format!("HELLO_REQ signature verification failed: {}", e)))?;

    Ok(qd_bytes)
}

/// Output of a successfully processed HELLO_RSP.
pub struct HandshakeResult {
    pub session_key: SessionKey,
    pub sequence_tracker: SequenceTracker,
    pub negotiated_version: Option<String>,
}

/// Parses and validates the wallet's HELLO_RSP:
/// `<Qw (65 bytes)><session_props (optional encrypted frame)>`
///
/// 1. Extracts wallet ephemeral public key Qw.
/// 2. Derives session AES-128 key via HKDF using Qa as salt.
/// 3. If session_props is present, decrypts it (seq=1) and validates session properties.
pub fn process_hello_rsp(
    association_pub_bytes: &[u8; 65],
    dapp_ephemeral: &DappEphemeralKeypair,
    hello_rsp_bytes: &[u8],
) -> Result<HandshakeResult> {
    if hello_rsp_bytes.len() < 65 {
        return Err(ShaheenError::HandshakeError(format!(
            "HELLO_RSP too short: expected at least 65 bytes, got {}",
            hello_rsp_bytes.len()
        )));
    }

    let qw_bytes = &hello_rsp_bytes[0..65];
    let dapp_priv = dapp_ephemeral.secret_key()?;

    // Derive the shared AES-128 key
    let session_key = derive_session_key(&dapp_priv, qw_bytes, association_pub_bytes)?;
    let mut sequence_tracker = SequenceTracker::new();

    let negotiated_version = if hello_rsp_bytes.len() > 65 {
        // Encrypted session_props message is present (MWA 2.0)
        let encrypted_props = &hello_rsp_bytes[65..];
        let (seq, decrypted_props) = decrypt_mwa_message(&session_key, encrypted_props)?;
        
        // Sequence must be 1 for the first message received from wallet
        sequence_tracker.validate_and_update_recv(seq)?;

        #[derive(serde::Deserialize)]
        struct SessionProps {
            v: Option<String>,
        }

        let props: SessionProps = serde_json::from_slice(&decrypted_props)
            .map_err(|e| ShaheenError::HandshakeError(format!("Failed to parse session_props: {}", e)))?;
        props.v
    } else {
        None
    };

    Ok(HandshakeResult {
        session_key,
        sequence_tracker,
        negotiated_version,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::encrypt_mwa_message;

    #[test]
    fn test_hello_req_and_rsp_handshake_flow() {
        // 1. Dapp creates association keypair
        let assoc = AssociationKeypair::generate().unwrap();

        // 2. Dapp creates ephemeral keypair
        let dapp_ephemeral = DappEphemeralKeypair::generate().unwrap();

        // 3. Dapp builds HELLO_REQ
        let hello_req = build_hello_req(&assoc, &dapp_ephemeral).unwrap();
        assert_eq!(hello_req.len(), 129);

        // 4. Wallet receives and verifies HELLO_REQ
        let verified_qd = verify_hello_req(&assoc.public_key_bytes, &hello_req).unwrap();
        assert_eq!(verified_qd, dapp_ephemeral.public_key_bytes);

        // 5. Wallet generates ephemeral keypair
        let wallet_priv = SecretKey::random(&mut OsRng);
        let wallet_pub = wallet_priv.public_key();
        let wallet_pub_bytes = wallet_pub.to_encoded_point(false);

        // Wallet derives shared key
        let wallet_session_key = derive_session_key(
            &wallet_priv,
            &verified_qd,
            &assoc.public_key_bytes,
        ).unwrap();

        // Wallet creates encrypted session_props with seq=1
        let session_props_json = b"{\"v\":\"2\"}";
        let encrypted_props = encrypt_mwa_message(&wallet_session_key, 1, session_props_json).unwrap();

        // Wallet builds HELLO_RSP: Qw || encrypted_props
        let mut hello_rsp = Vec::new();
        hello_rsp.extend_from_slice(wallet_pub_bytes.as_bytes());
        hello_rsp.extend_from_slice(&encrypted_props);

        // 6. Dapp processes HELLO_RSP
        let handshake_res = process_hello_rsp(
            &assoc.public_key_bytes,
            &dapp_ephemeral,
            &hello_rsp,
        ).unwrap();

        assert_eq!(handshake_res.session_key.as_bytes(), wallet_session_key.as_bytes());
        assert_eq!(handshake_res.negotiated_version.as_deref(), Some("2"));
        assert_eq!(handshake_res.sequence_tracker.last_recv_sequence(), Some(1));
    }
}
