
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.shaheen;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeShaheenSpecSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "ShaheenModule";

  public NativeShaheenSpecSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void createSession(double port, Promise promise);

  @ReactMethod
  @DoNotStrip
  public void launchWalletIntent(String uri, Promise promise) {}

  @ReactMethod
  @DoNotStrip
  public abstract void connectAndAuthorizeSession(String sessionId, String wsUrl, String chain, String authToken, String identityName, String identityUri, String identityIcon, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void signAndSend(String sessionId, String txPayloadsJson, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void signTransactions(String sessionId, String txPayloadsJson, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void signMessages(String sessionId, String addressesJson, String payloadsJson, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCapabilities(String sessionId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void deauthorize(String sessionId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void closeSession(String sessionId, Promise promise);
}
