
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "ShaheenSpec.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_createSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "createSession", "(DLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_launchWalletIntent(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "launchWalletIntent", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_connectAndAuthorizeSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "connectAndAuthorizeSession", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_signAndSend(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "signAndSend", "(Ljava/lang/String;Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_signTransactions(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "signTransactions", "(Ljava/lang/String;Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_signMessages(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "signMessages", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_getCapabilities(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getCapabilities", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_deauthorize(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "deauthorize", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeShaheenSpecSpecJSI_closeSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "closeSession", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeShaheenSpecSpecJSI::NativeShaheenSpecSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["createSession"] = MethodMetadata {1, __hostFunction_NativeShaheenSpecSpecJSI_createSession};
  methodMap_["launchWalletIntent"] = MethodMetadata {1, __hostFunction_NativeShaheenSpecSpecJSI_launchWalletIntent};
  methodMap_["connectAndAuthorizeSession"] = MethodMetadata {7, __hostFunction_NativeShaheenSpecSpecJSI_connectAndAuthorizeSession};
  methodMap_["signAndSend"] = MethodMetadata {2, __hostFunction_NativeShaheenSpecSpecJSI_signAndSend};
  methodMap_["signTransactions"] = MethodMetadata {2, __hostFunction_NativeShaheenSpecSpecJSI_signTransactions};
  methodMap_["signMessages"] = MethodMetadata {3, __hostFunction_NativeShaheenSpecSpecJSI_signMessages};
  methodMap_["getCapabilities"] = MethodMetadata {1, __hostFunction_NativeShaheenSpecSpecJSI_getCapabilities};
  methodMap_["deauthorize"] = MethodMetadata {1, __hostFunction_NativeShaheenSpecSpecJSI_deauthorize};
  methodMap_["closeSession"] = MethodMetadata {1, __hostFunction_NativeShaheenSpecSpecJSI_closeSession};
}

std::shared_ptr<TurboModule> ShaheenSpec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "ShaheenModule") {
    return std::make_shared<NativeShaheenSpecSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
