/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


#pragma mark - NativeShaheenSpecShaheenAccount

template <typename P0, typename P1, typename P2>
struct NativeShaheenSpecShaheenAccount {
  P0 address{};
  P1 displayAddress{};
  P2 label;
  bool operator==(const NativeShaheenSpecShaheenAccount &other) const {
    return address == other.address && displayAddress == other.displayAddress && label == other.label;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenAccountBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.address)>(rt, value.getProperty(rt, "address"), jsInvoker),
      bridging::fromJs<decltype(types.displayAddress)>(rt, value.getProperty(rt, "displayAddress"), jsInvoker),
      bridging::fromJs<decltype(types.label)>(rt, value.getProperty(rt, "label"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String addressToJs(jsi::Runtime &rt, decltype(types.address) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String displayAddressToJs(jsi::Runtime &rt, decltype(types.displayAddress) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String labelToJs(jsi::Runtime &rt, decltype(types.label) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "address", bridging::toJs(rt, value.address, jsInvoker));
    if (value.displayAddress) {
      result.setProperty(rt, "displayAddress", bridging::toJs(rt, value.displayAddress.value(), jsInvoker));
    }
    if (value.label) {
      result.setProperty(rt, "label", bridging::toJs(rt, value.label.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenAuthorizeSessionResult

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5>
struct NativeShaheenSpecShaheenAuthorizeSessionResult {
  P0 success{};
  P1 authToken{};
  P2 publicKey{};
  P3 accounts{};
  P4 errorCode{};
  P5 error;
  bool operator==(const NativeShaheenSpecShaheenAuthorizeSessionResult &other) const {
    return success == other.success && authToken == other.authToken && publicKey == other.publicKey && accounts == other.accounts && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenAuthorizeSessionResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.authToken)>(rt, value.getProperty(rt, "authToken"), jsInvoker),
      bridging::fromJs<decltype(types.publicKey)>(rt, value.getProperty(rt, "publicKey"), jsInvoker),
      bridging::fromJs<decltype(types.accounts)>(rt, value.getProperty(rt, "accounts"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String authTokenToJs(jsi::Runtime &rt, decltype(types.authToken) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String publicKeyToJs(jsi::Runtime &rt, decltype(types.publicKey) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array accountsToJs(jsi::Runtime &rt, decltype(types.accounts) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    result.setProperty(rt, "authToken", bridging::toJs(rt, value.authToken, jsInvoker));
    result.setProperty(rt, "publicKey", bridging::toJs(rt, value.publicKey, jsInvoker));
    result.setProperty(rt, "accounts", bridging::toJs(rt, value.accounts, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenDeauthorizeResult

template <typename P0, typename P1, typename P2>
struct NativeShaheenSpecShaheenDeauthorizeResult {
  P0 success{};
  P1 errorCode{};
  P2 error;
  bool operator==(const NativeShaheenSpecShaheenDeauthorizeResult &other) const {
    return success == other.success && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenDeauthorizeResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenGetCapabilitiesResult

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6>
struct NativeShaheenSpecShaheenGetCapabilitiesResult {
  P0 success{};
  P1 maxTransactionsPerRequest{};
  P2 maxMessagesPerRequest{};
  P3 supportedTransactionVersions{};
  P4 features{};
  P5 errorCode{};
  P6 error;
  bool operator==(const NativeShaheenSpecShaheenGetCapabilitiesResult &other) const {
    return success == other.success && maxTransactionsPerRequest == other.maxTransactionsPerRequest && maxMessagesPerRequest == other.maxMessagesPerRequest && supportedTransactionVersions == other.supportedTransactionVersions && features == other.features && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenGetCapabilitiesResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.maxTransactionsPerRequest)>(rt, value.getProperty(rt, "maxTransactionsPerRequest"), jsInvoker),
      bridging::fromJs<decltype(types.maxMessagesPerRequest)>(rt, value.getProperty(rt, "maxMessagesPerRequest"), jsInvoker),
      bridging::fromJs<decltype(types.supportedTransactionVersions)>(rt, value.getProperty(rt, "supportedTransactionVersions"), jsInvoker),
      bridging::fromJs<decltype(types.features)>(rt, value.getProperty(rt, "features"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static double maxTransactionsPerRequestToJs(jsi::Runtime &rt, decltype(types.maxTransactionsPerRequest) value) {
    return bridging::toJs(rt, value);
  }
  static double maxMessagesPerRequestToJs(jsi::Runtime &rt, decltype(types.maxMessagesPerRequest) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array supportedTransactionVersionsToJs(jsi::Runtime &rt, decltype(types.supportedTransactionVersions) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array featuresToJs(jsi::Runtime &rt, decltype(types.features) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    if (value.maxTransactionsPerRequest) {
      result.setProperty(rt, "maxTransactionsPerRequest", bridging::toJs(rt, value.maxTransactionsPerRequest.value(), jsInvoker));
    }
    if (value.maxMessagesPerRequest) {
      result.setProperty(rt, "maxMessagesPerRequest", bridging::toJs(rt, value.maxMessagesPerRequest.value(), jsInvoker));
    }
    result.setProperty(rt, "supportedTransactionVersions", bridging::toJs(rt, value.supportedTransactionVersions, jsInvoker));
    result.setProperty(rt, "features", bridging::toJs(rt, value.features, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenSessionInfo

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6>
struct NativeShaheenSpecShaheenSessionInfo {
  P0 success{};
  P1 sessionId{};
  P2 uri{};
  P3 port{};
  P4 associationToken{};
  P5 errorCode{};
  P6 error;
  bool operator==(const NativeShaheenSpecShaheenSessionInfo &other) const {
    return success == other.success && sessionId == other.sessionId && uri == other.uri && port == other.port && associationToken == other.associationToken && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenSessionInfoBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.sessionId)>(rt, value.getProperty(rt, "sessionId"), jsInvoker),
      bridging::fromJs<decltype(types.uri)>(rt, value.getProperty(rt, "uri"), jsInvoker),
      bridging::fromJs<decltype(types.port)>(rt, value.getProperty(rt, "port"), jsInvoker),
      bridging::fromJs<decltype(types.associationToken)>(rt, value.getProperty(rt, "associationToken"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String sessionIdToJs(jsi::Runtime &rt, decltype(types.sessionId) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String uriToJs(jsi::Runtime &rt, decltype(types.uri) value) {
    return bridging::toJs(rt, value);
  }
  static double portToJs(jsi::Runtime &rt, decltype(types.port) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String associationTokenToJs(jsi::Runtime &rt, decltype(types.associationToken) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    result.setProperty(rt, "sessionId", bridging::toJs(rt, value.sessionId, jsInvoker));
    result.setProperty(rt, "uri", bridging::toJs(rt, value.uri, jsInvoker));
    result.setProperty(rt, "port", bridging::toJs(rt, value.port, jsInvoker));
    result.setProperty(rt, "associationToken", bridging::toJs(rt, value.associationToken, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    if (value.error) {
      result.setProperty(rt, "error", bridging::toJs(rt, value.error.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenSignAndSendResult

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeShaheenSpecShaheenSignAndSendResult {
  P0 success{};
  P1 signatures{};
  P2 signature{};
  P3 errorCode{};
  P4 error;
  bool operator==(const NativeShaheenSpecShaheenSignAndSendResult &other) const {
    return success == other.success && signatures == other.signatures && signature == other.signature && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenSignAndSendResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.signatures)>(rt, value.getProperty(rt, "signatures"), jsInvoker),
      bridging::fromJs<decltype(types.signature)>(rt, value.getProperty(rt, "signature"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array signaturesToJs(jsi::Runtime &rt, decltype(types.signatures) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String signatureToJs(jsi::Runtime &rt, decltype(types.signature) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    result.setProperty(rt, "signatures", bridging::toJs(rt, value.signatures, jsInvoker));
    result.setProperty(rt, "signature", bridging::toJs(rt, value.signature, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenSignMessagesResult

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeShaheenSpecShaheenSignMessagesResult {
  P0 success{};
  P1 signedPayloads{};
  P2 signedPayload{};
  P3 errorCode{};
  P4 error;
  bool operator==(const NativeShaheenSpecShaheenSignMessagesResult &other) const {
    return success == other.success && signedPayloads == other.signedPayloads && signedPayload == other.signedPayload && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenSignMessagesResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.signedPayloads)>(rt, value.getProperty(rt, "signedPayloads"), jsInvoker),
      bridging::fromJs<decltype(types.signedPayload)>(rt, value.getProperty(rt, "signedPayload"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array signedPayloadsToJs(jsi::Runtime &rt, decltype(types.signedPayloads) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String signedPayloadToJs(jsi::Runtime &rt, decltype(types.signedPayload) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    result.setProperty(rt, "signedPayloads", bridging::toJs(rt, value.signedPayloads, jsInvoker));
    result.setProperty(rt, "signedPayload", bridging::toJs(rt, value.signedPayload, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};



#pragma mark - NativeShaheenSpecShaheenSignTransactionsResult

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeShaheenSpecShaheenSignTransactionsResult {
  P0 success{};
  P1 signedTxBase64{};
  P2 signedTxsBase64{};
  P3 errorCode{};
  P4 error;
  bool operator==(const NativeShaheenSpecShaheenSignTransactionsResult &other) const {
    return success == other.success && signedTxBase64 == other.signedTxBase64 && signedTxsBase64 == other.signedTxsBase64 && errorCode == other.errorCode && error == other.error;
  }
};

template <typename T>
struct NativeShaheenSpecShaheenSignTransactionsResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.success)>(rt, value.getProperty(rt, "success"), jsInvoker),
      bridging::fromJs<decltype(types.signedTxBase64)>(rt, value.getProperty(rt, "signedTxBase64"), jsInvoker),
      bridging::fromJs<decltype(types.signedTxsBase64)>(rt, value.getProperty(rt, "signedTxsBase64"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.error)>(rt, value.getProperty(rt, "error"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool successToJs(jsi::Runtime &rt, decltype(types.success) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String signedTxBase64ToJs(jsi::Runtime &rt, decltype(types.signedTxBase64) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array signedTxsBase64ToJs(jsi::Runtime &rt, decltype(types.signedTxsBase64) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String errorToJs(jsi::Runtime &rt, decltype(types.error) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "success", bridging::toJs(rt, value.success, jsInvoker));
    result.setProperty(rt, "signedTxBase64", bridging::toJs(rt, value.signedTxBase64, jsInvoker));
    result.setProperty(rt, "signedTxsBase64", bridging::toJs(rt, value.signedTxsBase64, jsInvoker));
    if (value.errorCode) {
      result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode.value(), jsInvoker));
    }
    result.setProperty(rt, "error", bridging::toJs(rt, value.error, jsInvoker));
    return result;
  }
};


template <typename T>
class JSI_EXPORT NativeShaheenSpecCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "ShaheenModule";

protected:
  NativeShaheenSpecCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeShaheenSpecCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["createSession"] = MethodMetadata {.argCount = 1, .invoker = __createSession};
    methodMap_["launchWalletIntent"] = MethodMetadata {.argCount = 1, .invoker = __launchWalletIntent};
    methodMap_["connectAndAuthorizeSession"] = MethodMetadata {.argCount = 7, .invoker = __connectAndAuthorizeSession};
    methodMap_["signAndSend"] = MethodMetadata {.argCount = 2, .invoker = __signAndSend};
    methodMap_["signTransactions"] = MethodMetadata {.argCount = 2, .invoker = __signTransactions};
    methodMap_["signMessages"] = MethodMetadata {.argCount = 3, .invoker = __signMessages};
    methodMap_["getCapabilities"] = MethodMetadata {.argCount = 1, .invoker = __getCapabilities};
    methodMap_["deauthorize"] = MethodMetadata {.argCount = 1, .invoker = __deauthorize};
    methodMap_["closeSession"] = MethodMetadata {.argCount = 1, .invoker = __closeSession};
  }
  
private:
  static jsi::Value __createSession(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::createSession) == 2,
      "Expected createSession(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::createSession,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());
  }

  static jsi::Value __launchWalletIntent(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::launchWalletIntent) == 2,
      "Expected launchWalletIntent(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::launchWalletIntent,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __connectAndAuthorizeSession(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::connectAndAuthorizeSession) == 8,
      "Expected connectAndAuthorizeSession(...) to have 8 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::connectAndAuthorizeSession,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asString(rt),
      count <= 3 ? throw jsi::JSError(rt, "Expected argument in position 3 to be passed") : args[3].asString(rt),
      count <= 4 ? throw jsi::JSError(rt, "Expected argument in position 4 to be passed") : args[4].asString(rt),
      count <= 5 ? throw jsi::JSError(rt, "Expected argument in position 5 to be passed") : args[5].asString(rt),
      count <= 6 ? throw jsi::JSError(rt, "Expected argument in position 6 to be passed") : args[6].asString(rt));
  }

  static jsi::Value __signAndSend(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::signAndSend) == 3,
      "Expected signAndSend(...) to have 3 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::signAndSend,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));
  }

  static jsi::Value __signTransactions(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::signTransactions) == 3,
      "Expected signTransactions(...) to have 3 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::signTransactions,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));
  }

  static jsi::Value __signMessages(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::signMessages) == 4,
      "Expected signMessages(...) to have 4 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::signMessages,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asString(rt));
  }

  static jsi::Value __getCapabilities(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::getCapabilities) == 2,
      "Expected getCapabilities(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getCapabilities,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __deauthorize(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::deauthorize) == 2,
      "Expected deauthorize(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::deauthorize,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __closeSession(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::closeSession) == 2,
      "Expected closeSession(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::closeSession,  static_cast<NativeShaheenSpecCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }
};

} // namespace facebook::react
